jobs: 128
cluster-sync:
  mkdir -p slurm-logs/{rule}/ &&
  sbatch
  --wait
  --partition={resources.partition}
  --cpus-per-task={resources.cpus}
  --job-name={rule}-{wildcards}
  --mem={resources.mem}
  --time={resources.time}
  --output=slurm-logs/{rule}/{rule}-{wildcards}-%j.out
  --exclude=compute-0-18
default-resources:
  - partition='good_lab_large_cpu'
  - mem='4g'
  - time='4:00:00'
  - cpus=1
latency-wait: 20
verbose: true
